"""deliting email from user model

Revision ID: 09360c64f072
Revises: fd211160fc8d
Create Date: 2022-08-10 13:50:46.738420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09360c64f072'
down_revision = 'fd211160fc8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
