"""some changes

Revision ID: 2781535f54fd
Revises: 2d6ebe152a8d
Create Date: 2022-08-12 15:40:04.222114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2781535f54fd'
down_revision = '2d6ebe152a8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('category_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'category_name')
    # ### end Alembic commands ###
