"""relationship between Category and cards

Revision ID: 2d6ebe152a8d
Revises: 4f2c7f0214b9
Create Date: 2022-08-12 14:52:23.286356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d6ebe152a8d'
down_revision = '4f2c7f0214b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'card', 'category', ['category_id'], ['category_id'])
    op.drop_column('card', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_column('card', 'category_id')
    # ### end Alembic commands ###
