"""adding User model

Revision ID: 466c82105a66
Revises: 8f70d08473a8
Create Date: 2022-08-09 13:50:28.414837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '466c82105a66'
down_revision = '8f70d08473a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('confirmed_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
