"""adds Card model

Revision ID: cc58c370a9e5
Revises: 09360c64f072
Create Date: 2022-08-12 13:12:06.103829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc58c370a9e5'
down_revision = '09360c64f072'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('card_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('correct_answer', sa.String(), nullable=True),
    sa.Column('incorrect_answer1', sa.String(), nullable=True),
    sa.Column('incorrect_answer2', sa.String(), nullable=True),
    sa.Column('incorrect_answer3', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('card_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card')
    # ### end Alembic commands ###
