"""Adding models

Revision ID: ea12396c058a
Revises: 
Create Date: 2022-08-09 18:18:37.806773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea12396c058a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz',
    sa.Column('question_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('correct_answer', sa.String(), nullable=True),
    sa.Column('incorrect_answer1', sa.String(), nullable=True),
    sa.Column('incorrect_answer2', sa.String(), nullable=True),
    sa.Column('incorrect_answer3', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('confirmed_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('quiz')
    # ### end Alembic commands ###
